language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: xenial

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.6
    - os: osx
      language: generic
      env: PYTHON_VER=3.7

    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6
    - os: linux
      python: 3.7
      env: PYTHON_VER=3.7

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Pull down a miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
    # set to always say yes to conda install
  - conda config --set always_yes yes --set changeps1 no
    # makes installs a little more quiet so you get less output
  - conda update -q conda
  - conda info -a
    # creates environment for the given python version
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy pytest 
  - source activate test
  - conda install -c openeye openeye-toolkits

    # Create test environment for package
  - conda create -n test python=$PYTHON_VER pip pytest pytest-cov
  - conda activate test

    # Install pip only modules
  - pip install codecov

    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --use-local quanformer


script:
  - pytest -v --cov=quanformer quanformer/tests/

global:
  - OE_LICENSE="$HOME/oe_license.txt"

notifications:
    email: false

after_success:
  - codecov
