language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.6
    - os: osx
      language: generic
      env: PYTHON_VER=3.7

    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6
    - os: linux
      python: 3.7
      env: PYTHON_VER=3.7

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_f0234faf2f39_key -iv $encrypted_f0234faf2f39_iv -in oe_license.txt.enc -out oe_license.txt -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ]; then echo "OpenEye license will not be installed in forks."; fi

install:
    # Pull down a miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
    # set to always say yes to conda install
  - conda config --set always_yes yes --set changeps1 no
    # makes installs a little more quiet so you get less output
  - conda update -q conda
  - conda info -a
    # creates environment for the given python version
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION numpy pytest 
  - source activate test
  - conda install -c openeye openeye-toolkits

    # Install anything not in conda
  - pip install codecov
  - pip install pytest-cov
  - conda list

    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --use-local quanformer


script:
  - pytest -v -s --cov=quanformer quanformer/tests/

global:
  - OE_LICENSE="$HOME/oe_license.txt"

notifications:
    email: false

after_success:
  - codecov
